### ISSUE TITLE
Header Merge Fixes

### ISSUE THREAD

**Issue by adamrichardturner** [dogdb-org/dogdb-frontend#27]
The merge of the header component created some minor issues, I lets fix these, including Next.js warnings.

**Comment by adamrichardturner** [comment]
@skoly1 Sai, please can you git pull the latest main and create a branch to help us fix these issues. it will be a good exercise in debugging and I want everyone to view the changes.

I have commented out the Header component in Layout.tsx, there are still some warnings and issues related to Redux, but I have removed the duplicate prettier config and updated contribution doc and package.json scripts - please check these out.

**Comment by skoly1** [comment]
The warning are related hydration error warnings when there is a mismatch between server rendered and client rendered component. 
Check this for more details on this: [https://github.com/chakra-ui/chakra-ui/issues/7040](url)
