### ISSUE TITLE
Set up continuous deployment of FE on VPS

### ISSUE THREAD

**Issue by adamrichardturner** [dogdb-org/dogdb-frontend#63]
Set up a continuous deployment of the dogdb-frontend main branch on the VPS using GitHub actions.

https://dev.to/knowbee/how-to-setup-continuous-deployment-of-a-website-on-a-vps-using-github-actions-54im

**Comment by elidakirigo** [comment]
awesome. I hope we can get success or failed outputs on pull requests on the main branch.
